### ISSUE TITLE
Investigate constructor benchmark

### ISSUE THREAD

**Issue by 0x0f0f0f** [nmheim/egg-benchmark#9]
Taking 87.8 nanoseconds only for constructing a bunch of hash tables is too little. https://github.com/JuliaSymbolics/Metatheory.jl/pull/185#issuecomment-1890910789

Maybe the rust compiler is optimizing and detecting that that object is going to be destroyed instantly and thus not allocating stuff?

**Comment by nmheim** [comment]
Hmm, I don't know, with julia 1.11 I am getting something even faster for the Metatheory.jl constructor:

```julia
julia> @btime EGraph()
  46.633 ns (12 allocations: 704 bytes)
```

**Comment by nmheim** [comment]
The numbers get a bit better in general with julia 1.11 actually;) maybe we should move the benchmark CI workflow to 1.11?
Locally I am getting

|                                 | egg-sym   | egg-cust | MT@ale/3.0 | MT@master   | egg-sym/MT@ale... | egg-cust/MT@al... | MT@master/MT@a... |
|:--------------------------------|:---------:|:--------:|:----------:|:-----------:|:-----------------:|:-----------------:|:-----------------:|
| egraph_addexpr                  | 757 μs    |          | 3.81 ms    | 11.2 ms     | 0.199             |                   | 2.93              |
| basic_maths_simpl2              | 8.25 ms   | 3.58 ms  | 14.9 ms    | 598 ms      | 0.555             | 0.241             | 40.2              |
| prop_logic_freges_theorem       | 1.7 ms    | 1.12 ms  | 1.72 ms    | 27 ms       | 0.984             | 0.648             | 15.7              |
| calc_logic_demorgan             | 41.2 μs   | 25.1 μs  | 63.5 μs    | 348 μs      | 0.648             | 0.395             | 5.48              |
| calc_logic_freges_theorem       | 12.9 ms   | 2.13 ms  | 27.1 ms    | 2.34e+03 ms | 0.475             | 0.0787            | 86.4              |
| basic_maths_simpl1              | 4.14 ms   | 2.13 ms  | 4.5 ms     | 38.4 ms     | 0.92              | 0.474             | 8.54              |
| egraph_constructor              | 0.0557 μs |          | 0.042 μs   | 0.083 μs    | 1.33              |                   | 1.98              |
| prop_logic_prove1               | 21.9 ms   | 19.4 ms  | 29 ms      | 6.29e+03 ms | 0.755             | 0.668             | 217               |
| prop_logic_demorgan             | 56.4 μs   | 30 μs    | 71.2 μs    | 524 μs      | 0.793             | 0.422             | 7.36              |
| while_superinterpreter_while_10 |           |          | 12.4 ms    | 69.5 ms     |                   |                   | 5.6               |
| prop_logic_rewrite              |           |          | 79.5 μs    | 80.5 μs     |                   |                   | 1.01              |
| time_to_load                    |           |          | 329 ms     | 345 ms      |                   |                   | 1.05              |
